name: rime-ice

on:
  workflow_dispatch:
jobs:
  awa:
    runs-on: ubuntu-latest
    steps:
        
      - name: 好吃的
        run: |
          export w=$(curl -s -L https://api.github.com/repos/iDvel/rime-ice | jq .pushed_at | awk -F "[-,=,:]" '{print $1"_"$2"_"$3"_"$4"_"$5}')
          export u=$(curl -s -L "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=rime-ice" | jq .results[].Version)
          if test $w = $u; then echo "www=yes" >> $GITHUB_ENV; fi
          if test $w = $u; then echo "www=yes"; fi
          echo $w
          echo $u
      - name: www
        if: ${{ env.www }} == yes
        run: |
          echo ${{ env.www }}
        
      
          
      
        
