name: rime-ice

on:
  workflow_dispatch:
jobs:
  awa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        name: 当前版本
        with:
          key: rime-ice
          path: |
            current
        
      - name: 好吃的
        run: |
          export w=$(curl -s -L https://api.github.com/repos/iDvel/rime-ice/git/refs/heads/main | jq .object.url)
          export u=$(cat current)
          echo ${w} > current
          if test $w = $u; then echo www; fi # 不同的step不是同一个bash(悲
      
          
      
        
