name: rime-ice

on:
  workflow_dispatch:
jobs:
  awa:
    runs-on: ubuntu-latest
    steps:
        
      - name: 好吃的
        run: |
          export w=$(curl -s -L https://api.github.com/repos/iDvel/rime-ice | jq .pushed_at | awk -F "[-,=,:]" '{print $1"_"$2"_"$3"_"$4"_"$5}' | sed 's/\"//g')"-1"
          export u=$(curl -s -L "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=rime-ice" | jq .results[].Version | sed 's/\"//g')
          if test $w = $u; then echo "www=1" >> $GITHUB_ENV; else echo "www=0" >> $GITHUB_ENV; fi
          echo "uuu=$w" >> $GITHUB_ENV
          echo $w
          echo $u
      - name: www
        run: |
          if test ${{ env.www }} = 0;then
          git clone ssh://aur@aur.archlinux.org/rime-ice.git
          cd rime-ice/
          sed -i "s/pkgver=.*/pkgver=${{ env.uuu }}/g" PKGBUILD
          sed -i "s/pkgver = .*/pkgver = ${{ env.uuu }}/g" .SRCINFO
          fi
          echo "${{ secrets.AUR_SSH_PUBLIC_KEY }}"
        
      
          
      
        
